/* ============================================================
   BooM 💥 — Banque de situations
   4 niveaux : doux, piquant, coquin, brulant
   Le jeton {cible} est remplacé par un prénom choisi par le joueur
   quand avecQui = true (le joueur désigne quelqu'un du groupe).
   ============================================================ */

const NIVEAUX = [
  { id: "doux",    nom: "Doux 🌤️",     couleur: "#7CD1B8" },
  { id: "piquant", nom: "Piquant 🌶️",  couleur: "#F2B441" },
  { id: "coquin",  nom: "Coquin 😏",    couleur: "#F2617A" },
  { id: "brulant", nom: "Brûlant 🔥",   couleur: "#C4336B" },
  { id: "defi",    nom: "Défi 🎯",      couleur: "#4FA8E0" },
];

// niveau, texte, avecQui, defi (validation manuelle fait/pas fait), libre (texte écrit par la Cible)
function c(niveau, texte, avecQui = false, defi = false, libre = false) {
  return { niveau, texte, avecQui, defi, libre };
}

const CARTES_BRUTES = [
  // ------------------------------------------------------------
  // DOUX — quotidien, absurde, inoffensif
  // ------------------------------------------------------------
  c("doux", "Manger des huîtres au petit déjeuner"),
  c("doux", "Chanter sous la douche à pleins poumons"),
  c("doux", "Porter des chaussettes dépareillées toute une semaine par choix"),
  c("doux", "Dormir avec la lumière allumée"),
  c("doux", "Manger de la pizza à l'ananas"),
  c("doux", "Faire du camping sans tente, à la belle étoile"),
  c("doux", "Apprendre le jonglage en une semaine"),
  c("doux", "Adopter un furet"),
  c("doux", "Aller au travail en pyjama un jour"),
  c("doux", "Passer une journée entière sans réseaux sociaux"),
  c("doux", "Manger uniquement des aliments orange pendant une journée"),
  c("doux", "Te réveiller à 5h du matin pour voir le lever du soleil"),
  c("doux", "Apprendre trois mots de klingon"),
  c("doux", "Porter un chapeau ridicule toute une soirée"),
  c("doux", "Faire du vélo sous la pluie sans imperméable"),
  c("doux", "Manger un plat que tu détestais enfant"),
  c("doux", "Passer un dimanche entier sans dire un mot"),
  c("doux", "Danser seul·e dans le salon pendant dix minutes"),
  c("doux", "Te déguiser en super-héros pour aller faire les courses"),
  c("doux", "Écrire une lettre à la main à un vieil ami"),
  c("doux", "Goûter à un insecte comestible"),
  c("doux", "Apprendre à faire une roulade avant"),
  c("doux", "Partir en week-end à Cracovie sans réserver l'hôtel à l'avance"),
  c("doux", "Faire un régime sans sucre pendant une semaine"),
  c("doux", "Prendre un bain glacé de deux minutes"),
  c("doux", "Assister à un opéra sans jamais y être allé"),
  c("doux", "Manger avec des baguettes pendant une semaine entière"),
  c("doux", "Te lancer dans un puzzle de 2000 pièces ce week-end"),
  c("doux", "Faire un triathlon l'année prochaine"),
  c("doux", "Passer une soirée sans écran, juste des bougies"),
  c("doux", "Adopter un accent différent pendant une journée entière"),
  c("doux", "Te lever et courir 5 km avant le travail demain"),
  c("doux", "Cuisiner un plat d'un pays que tu ne connais pas"),
  c("doux", "Faire du stand-up devant des inconnus"),
  c("doux", "Prendre des cours de poterie"),
  c("doux", "Dormir dans une cabane dans les arbres"),
  c("doux", "Passer une journée à parler uniquement en rimes"),
  c("doux", "Manger un citron entier comme une orange"),
  c("doux", "Aller au cinéma tout seul un samedi soir"),
  c("doux", "Faire un don anonyme à quelqu'un que tu connais"),
  c("doux", "Te faire couper les cheveux très courts"),
  c("doux", "Apprendre à faire du feu sans allumettes"),
  c("doux", "Manger un plat entièrement de couleur noire (activated charcoal)"),
  c("doux", "Passer 24h sans te plaindre de rien"),
  c("doux", "Faire un marathon de films d'horreur toute une nuit"),
  c("doux", "Apprendre à lire dans les cartes de tarot"),
  c("doux", "Sauter en parachute cette année"),
  c("doux", "Suivre un cours de salsa avec {cible}", true),
  c("doux", "Partir en randonnée de nuit avec {cible}", true),
  c("doux", "Cuisiner un brunch complet pour {cible} demain matin", true),
  c("doux", "", true, false, true),
  c("doux", "", true, false, true),

  // ------------------------------------------------------------
  // PIQUANT — social, un peu gênant, drôle
  // ------------------------------------------------------------
  c("piquant", "T'exhiber torse nu (ou en soutien-gorge) dans un lieu public"),
  c("piquant", "Envoyer un message vocal chantant à ton patron"),
  c("piquant", "Appeler ton ex pour lui souhaiter bonne nuit, là, maintenant"),
  c("piquant", "Publier une photo embarrassante de toi sur tes réseaux"),
  c("piquant", "Draguer la première personne que tu croises demain, juste pour voir"),
  c("piquant", "Raconter ton pire souvenir de soirée devant tout le monde"),
  c("piquant", "Avouer la dernière fois que tu as menti à quelqu'un ici"),
  c("piquant", "Faire un strip-tease (habillé) sur une chanson imposée par le groupe"),
  c("piquant", "Montrer les cinq dernières photos de ta galerie sans filtre"),
  c("piquant", "Laisser {cible} lire tes trois derniers messages", true),
  c("piquant", "Danser un slow très lentement avec {cible} devant tout le monde", true),
  c("piquant", "Faire un compliment ultra-embarrassant à {cible} devant le groupe", true),
  c("piquant", "Envoyer un texto coquin à {cible} là, maintenant", true),
  c("piquant", "Avouer à {cible} ce que tu penses vraiment de lui/elle", true),
  c("piquant", "Faire un câlin de trente secondes à {cible}, minuté", true),
  c("piquant", "Sortir en soirée sans téléphone, complètement déconnecté"),
  c("piquant", "Embrasser {cible} sur la joue en public", true),
  c("piquant", "Te faire masser les pieds par {cible} pendant deux minutes", true),
  c("piquant", "Partager ton dernier fantasme de voyage romantique devant tout le monde"),
  c("piquant", "Faire semblant d'être en couple avec {cible} devant des inconnus toute une soirée", true),
  c("piquant", "Chanter une chanson d'amour a cappella pour {cible}", true),
  c("piquant", "Raconter ta pire expérience de rendez-vous amoureux"),
  c("piquant", "Décrire ton type physique idéal sans filtre"),
  c("piquant", "Montrer la dernière photo que tu as prise de toi devant un miroir"),
  c("piquant", "Avouer qui, dans la pièce, tu trouves le plus charismatique"),
  c("piquant", "Laisser le groupe choisir ta photo de profil pour la semaine"),
  c("piquant", "Faire semblant de te déclarer à {cible} devant tout le monde", true),
  c("piquant", "Réciter un poème d'amour improvisé pour {cible}", true),
  c("piquant", "Partager le dernier rêve un peu bizarre que tu as fait"),
  c("piquant", "Avouer la chose la plus folle que tu as faite pour séduire quelqu'un"),
  c("piquant", "Te faire chatouiller pendant trente secondes par {cible}", true),
  c("piquant", "Faire un défilé de mode improvisé avec ce que tu portes"),
  c("piquant", "Décrire ta soirée parfaite en tête à tête avec {cible}", true),
  c("piquant", "Avouer la dernière fois où tu as eu un coup de cœur soudain"),
  c("piquant", "Faire deviner au groupe ton premier baiser, année et lieu"),
  c("piquant", "Envoyer une photo (habillée) de toi à {cible} sous les yeux du groupe", true),
  c("piquant", "Te laisser maquiller ou coiffer par {cible} pendant cinq minutes", true),
  c("piquant", "Partager ton dernier message doux envoyé à quelqu'un, sans dire à qui"),
  c("piquant", "Faire un massage d'épaules d'une minute à {cible}", true),
  c("piquant", "Avouer ce que tu as pensé en arrivant ce soir en voyant {cible}", true),
  c("piquant", "", true, false, true),
  c("piquant", "", true, false, true),

  // ------------------------------------------------------------
  // COQUIN — suggestif, allusif, assumé
  // ------------------------------------------------------------
  c("coquin", "Partir en week-end romantique à Cracovie avec {cible}", true),
  c("coquin", "Passer une nuit entière à discuter au lit avec {cible}, rien d'autre", true),
  c("coquin", "Faire un massage sensuel de deux minutes à {cible}", true),
  c("coquin", "Chuchoter quelque chose de coquin à l'oreille de {cible}", true),
  c("coquin", "Partager ton fantasme le plus doux, sans donner de détails crus"),
  c("coquin", "Danser un slow très rapproché avec {cible}, front contre front", true),
  c("coquin", "Avouer la dernière fois où tu as eu un frisson en pensant à quelqu'un"),
  c("coquin", "Écrire un mot doux et coquin à {cible} et le lui glisser discrètement", true),
  c("coquin", "Faire semblant d'être en lune de miel avec {cible} pendant toute la soirée", true),
  c("coquin", "Décrire ta tenue de nuit idéale pour un rendez-vous romantique"),
  c("coquin", "Passer la nuit à Cracovie dans la même chambre que {cible}, un seul lit", true),
  c("coquin", "Avouer qui, ici, tu embrasserais sans hésiter si le jeu te le demandait"),
  c("coquin", "Faire un baiser sur la main à {cible}, à l'ancienne", true),
  c("coquin", "Partager le souvenir le plus sensuel que tu gardes d'une soirée d'été"),
  c("coquin", "Proposer un rendez-vous romantique à {cible}, sérieusement, là tout de suite", true),
  c("coquin", "Décrire la scène romantique parfaite pour une première nuit avec quelqu'un"),
  c("coquin", "Faire durer un regard intense avec {cible} pendant dix secondes, sans rire", true),
  c("coquin", "Avouer ta plus grande faiblesse quand quelqu'un te séduit"),
  c("coquin", "Faire une déclaration passionnée à {cible}, façon film romantique", true),
  c("coquin", "Décrire le dessous ou vêtement de nuit que tu préfères porter"),
  c("coquin", "Avouer le compliment le plus troublant qu'on t'ait fait"),
  c("coquin", "Faire un jeu de mains coquin avec {cible}, juste les mains, une minute", true),
  c("coquin", "Partager ta chanson qui te met dans une ambiance sensuelle"),
  c("coquin", "Avouer si tu préfères qu'on te dévore des yeux ou des mots"),
  c("coquin", "Faire semblant de rougir en confiant un secret coquin au groupe"),
  c("coquin", "Décrire le premier geste que tu ferais en tête à tête avec {cible}", true),
  c("coquin", "Avouer la dernière fois où tu as mouillé d'excitation avant même le premier geste"),
  c("coquin", "Avouer la dernière fois où tu as bandé rien qu'en y pensant"),
  c("coquin", "Raconter ton réveil le plus sensuel, sans entrer dans les détails"),
  c("coquin", "Faire une promesse coquine à {cible} pour plus tard dans la soirée", true),
  c("coquin", "Avouer quel vêtement de {cible} tu aimerais lui enlever du regard, ce soir", true),
  c("coquin", "Décrire l'ambiance parfaite (musique, lumière) pour une nuit avec quelqu'un"),
  c("coquin", "Faire semblant de proposer le mariage à {cible}, à genoux", true),
  c("coquin", "Avouer si tu préfères recevoir ou donner les compliments au lit"),
  c("coquin", "Chuchoter un compte à rebours coquin à l'oreille de {cible}", true),
  c("coquin", "Raconter le baiser le plus mémorable de ta vie, sans nommer la personne"),
  c("coquin", "Faire une caresse sur le bras de {cible}, lentement, dix secondes", true),
  c("coquin", "Avouer ton fantasme de lieu insolite pour un tête-à-tête"),
  c("coquin", "Partager le mot que tu préfères entendre chuchoté à ton oreille"),
  c("coquin", "Avouer combien de fois tu as pensé à {cible} de façon coquine cette semaine", true),

  // — Version fruits, légumes & bestiaire (mêmes idées, en détourné) —
  c("coquin", "Avouer quel légume du marché te fait irrésistiblement penser à {cible}, et pourquoi", true),
  c("coquin", "Décrire {cible} en un seul fruit, avec la texture et la saison", true),
  c("coquin", "Avouer si tu te sens plutôt « pêche bien mûre » ou « ananas qui pique » ce soir"),
  c("coquin", "Choisir l'animal qui représenterait le mieux {cible} sous la couette, et imiter son cri trois secondes", true),
  c("coquin", "Avouer quelle pâtisserie te fait immanquablement penser à une nuit torride"),
  c("coquin", "Décrire, façon recette de cuisine et sans un mot cru, ce que tu ferais à {cible} ce soir", true),
  c("coquin", "Avouer ton animal totem quand tu es d'humeur coquine, et pourquoi"),
  c("coquin", "Choisir entre « banane », « concombre » ou « carotte » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Avouer quel fruit tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Décrire la texture idéale d'un fruit défendu, sans jamais donner le nom du fruit"),
  c("coquin", "Avouer si tu es plutôt « chaton qui griffe » ou « chaton qui ronronne »"),
  c("coquin", "Choisir un légume du potager pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Avouer quel animal tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Décrire {cible} comme un plat de menu : entrée, plat ou dessert ?", true),
  c("coquin", "Avouer la dernière fois où une simple courgette au marché t'a fait penser à tout autre chose"),
  c("coquin", "Choisir le fruit le plus juteux de la table et dire discrètement à qui il te fait penser"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à un verger bien rangé ou à une jungle épaisse"),
  c("coquin", "Décrire, en langage panier de fruits, ta nuit de rêve avec {cible}", true),
  c("coquin", "Avouer quel petit animal tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Choisir la meilleure métaphore culinaire pour décrire ton humeur du moment, devant tout le monde"),
  c("coquin", "Avouer quel duo fruit + légume résumerait le mieux une nuit avec {cible}", true),
  c("coquin", "Décrire, en une phrase et sans un mot cru, ce qui se passe quand le fruit est « bien mûr »"),


  // — Grande série additionnelle (fruits, légumes, bestiaire, sucreries) —
  c("coquin", "Avouer quelle framboise te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quel abricot te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quelle datte te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quelle grenade te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quel litchi te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quelle groseille te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quelle prune te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quelle poire te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Avouer quelle mangue te fait irrésistiblement penser à {cible} ce soir", true),
  c("coquin", "Décrire {cible} en une seule grenade, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en un seul litchi, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en une seule groseille, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en une seule prune, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en une seule poire, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en une seule mangue, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en une seule fraise, avec la texture et la saison", true),
  c("coquin", "Décrire {cible} en une seule mandarine, avec la texture et la saison", true),
  c("coquin", "Avouer si tu te sens plutôt « framboise mûre à point » ou « fraise bien sucrée » ce soir"),
  c("coquin", "Avouer si tu te sens plutôt « abricot tout fondant » ou « mandarine au bord de déborder » ce soir"),
  c("coquin", "Avouer si tu te sens plutôt « datte qui frétille » ou « pêche gourmande et pressée » ce soir"),
  c("coquin", "Avouer si tu te sens plutôt « grenade bien sucrée » ou « mirabelle toute chamboulée » ce soir"),
  c("coquin", "Avouer si tu te sens plutôt « litchi au bord de déborder » ou « ananas qui n'attend qu'un geste » ce soir"),
  c("coquin", "Avouer si tu te sens plutôt « groseille gourmande et pressée » ou « nectarine mûre à point » ce soir"),
  c("coquin", "Avouer si tu te sens plutôt « prune toute chamboulée » ou « cerise toute fondante » ce soir"),
  c("coquin", "Choisir l'artichaut qui te représenterait le mieux ce soir, et le présenter au groupe avec fierté"),
  c("coquin", "Choisir l'asperge qui te représenterait le mieux ce soir, et la présenter au groupe avec fierté"),
  c("coquin", "Choisir le concombre qui te représenterait le mieux ce soir, et le présenter au groupe avec fierté"),
  c("coquin", "Choisir le navet qui te représenterait le mieux ce soir, et le présenter au groupe avec fierté"),
  c("coquin", "Choisir la carotte qui te représenterait le mieux ce soir, et la présenter au groupe avec fierté"),
  c("coquin", "Choisir le radis qui te représenterait le mieux ce soir, et le présenter au groupe avec fierté"),
  c("coquin", "Choisir l'aubergine qui te représenterait le mieux ce soir, et la présenter au groupe avec fierté"),
  c("coquin", "Avouer quelle praline te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer quel miel te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer quelle guimauve te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer quel sucre d'orge te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer quelle meringue te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer quelle chantilly te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer quelle crème brûlée te fait immanquablement penser à une soirée un peu chaude"),
  c("coquin", "Avouer que ton animal totem (panthère ou paon) sort dès que l'ambiance devient coquine, et pourquoi"),
  c("coquin", "Avouer que ton animal totem (loutre ou biche) sort dès que l'ambiance devient coquine, et pourquoi"),
  c("coquin", "Avouer que ton animal totem (gazelle ou tigre) sort dès que l'ambiance devient coquine, et pourquoi"),
  c("coquin", "Avouer que ton animal totem (renard ou lynx) sort dès que l'ambiance devient coquine, et pourquoi"),
  c("coquin", "Avouer que ton animal totem (colibri ou chaton) sort dès que l'ambiance devient coquine, et pourquoi"),
  c("coquin", "Avouer que ton animal totem (paon ou ocelot) sort dès que l'ambiance devient coquine, et pourquoi"),
  c("coquin", "Choisir entre « artichaut », « navet » ou « aubergine » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Choisir entre « asperge », « carotte » ou « courgette » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Choisir entre « concombre », « radis » ou « piment » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Choisir entre « navet », « aubergine » ou « haricot vert » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Choisir entre « carotte », « courgette » ou « poireau » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Choisir entre « radis », « piment » ou « panais » pour résumer ton appétit du soir, et assumer le choix"),
  c("coquin", "Avouer quelle datte tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quelle grenade tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quel litchi tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quelle groseille tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quelle prune tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quelle poire tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quelle mangue tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer quelle fraise tu grignoterais volontiers en pensant à {cible}, sans rire", true),
  c("coquin", "Avouer si tu es plutôt « panthère qui griffe » ou « colibri qui ronronne »"),
  c("coquin", "Avouer si tu es plutôt « loutre qui griffe » ou « paon qui ronronne »"),
  c("coquin", "Avouer si tu es plutôt « gazelle qui griffe » ou « biche qui ronronne »"),
  c("coquin", "Avouer si tu es plutôt « renard qui griffe » ou « tigre qui ronronne »"),
  c("coquin", "Avouer si tu es plutôt « colibri qui griffe » ou « lynx qui ronronne »"),
  c("coquin", "Avouer si tu es plutôt « paon qui griffe » ou « chaton qui ronronne »"),
  c("coquin", "Choisir une asperge pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir un concombre pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir un navet pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir une carotte pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir un radis pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir une aubergine pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir une courgette pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Choisir un piment pour représenter ta soirée idéale avec {cible}, et le défendre trois secondes", true),
  c("coquin", "Avouer quel animal (panthère) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Avouer quel animal (loutre) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Avouer quel animal (gazelle) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Avouer quel animal (renard) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Avouer quel animal (colibri) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Avouer quel animal (paon) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Avouer quel animal (biche) tu deviendrais pour séduire {cible} ce soir, mime à l'appui", true),
  c("coquin", "Décrire {cible} comme un article du menu du soir : entrée, plat ou dessert, et pourquoi", true),
  c("coquin", "Avouer la dernière fois où un concombre au marché t'a fait penser à tout autre chose"),
  c("coquin", "Avouer la dernière fois où un navet au marché t'a fait penser à tout autre chose"),
  c("coquin", "Avouer la dernière fois où une carotte au marché t'a fait penser à tout autre chose"),
  c("coquin", "Avouer la dernière fois où un radis au marché t'a fait penser à tout autre chose"),
  c("coquin", "Avouer la dernière fois où une aubergine au marché t'a fait penser à tout autre chose"),
  c("coquin", "Avouer la dernière fois où une courgette au marché t'a fait penser à tout autre chose"),
  c("coquin", "Choisir la groseille la plus juteux(se) de la table et dire discrètement à qui il/elle te fait penser"),
  c("coquin", "Choisir la prune la plus juteux(se) de la table et dire discrètement à qui il/elle te fait penser"),
  c("coquin", "Choisir la poire la plus juteux(se) de la table et dire discrètement à qui il/elle te fait penser"),
  c("coquin", "Choisir la mangue la plus juteux(se) de la table et dire discrètement à qui il/elle te fait penser"),
  c("coquin", "Choisir la fraise la plus juteux(se) de la table et dire discrètement à qui il/elle te fait penser"),
  c("coquin", "Choisir la mandarine la plus juteux(se) de la table et dire discrètement à qui il/elle te fait penser"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à une serre tropicale bien rangé ou à un verger un peu fou"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à un jardin d'hiver bien rangé ou à un hamac sous les étoiles un peu fou"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à un jardin secret bien rangé ou à une cave à vin un peu fou"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à un verger bien rangé ou à un chalet au coin du feu un peu fou"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à un hamac sous les étoiles bien rangé ou à une ruche un peu fou"),
  c("coquin", "Avouer si ton jardin secret ressemble plus à une cave à vin bien rangé ou à un potager un peu fou"),
  c("coquin", "Décrire, en langage guimauve, ta soirée de rêve avec {cible}", true),
  c("coquin", "Décrire, en langage sucre d'orge, ta soirée de rêve avec {cible}", true),
  c("coquin", "Décrire, en langage meringue, ta soirée de rêve avec {cible}", true),
  c("coquin", "Décrire, en langage chantilly, ta soirée de rêve avec {cible}", true),
  c("coquin", "Décrire, en langage crème brûlée, ta soirée de rêve avec {cible}", true),
  c("coquin", "Décrire, en langage tablette de chocolat, ta soirée de rêve avec {cible}", true),
  c("coquin", "Décrire, en langage caramel, ta soirée de rêve avec {cible}", true),
  c("coquin", "Avouer quel petit animal (gazelle) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Avouer quel petit animal (renard) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Avouer quel petit animal (colibri) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Avouer quel petit animal (paon) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Avouer quel petit animal (biche) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Avouer quel petit animal (tigre) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Avouer quel petit animal (lynx) tu chuchoterais à l'oreille de {cible} pour le/la faire rougir", true),
  c("coquin", "Choisir la meilleure métaphore culinaire (praline, framboise...) pour décrire ton humeur du moment, devant tout le monde"),
  c("coquin", "Choisir la meilleure métaphore culinaire (miel, abricot...) pour décrire ton humeur du moment, devant tout le monde"),
  c("coquin", "Choisir la meilleure métaphore culinaire (guimauve, datte...) pour décrire ton humeur du moment, devant tout le monde"),
  c("coquin", "Choisir la meilleure métaphore culinaire (sucre d'orge, grenade...) pour décrire ton humeur du moment, devant tout le monde"),
  c("coquin", "Choisir la meilleure métaphore culinaire (meringue, litchi...) pour décrire ton humeur du moment, devant tout le monde"),
  c("coquin", "Avouer quel duo framboise + artichaut résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel duo abricot + asperge résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel duo datte + concombre résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel duo grenade + navet résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel duo litchi + carotte résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel duo groseille + radis résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel duo prune + aubergine résumerait le mieux une soirée avec {cible}", true),
  c("coquin", "Avouer quel poivre rose tu serais ce soir : douce, piquante, ou carrément explosive"),
  c("coquin", "Avouer quel gingembre tu serais ce soir : douce, piquante, ou carrément explosive"),
  c("coquin", "Avouer quelle cardamome tu serais ce soir : douce, piquante, ou carrément explosive"),
  c("coquin", "Avouer quel clou de girofle tu serais ce soir : douce, piquante, ou carrément explosive"),
  c("coquin", "Avouer quelle vanille tu serais ce soir : douce, piquante, ou carrément explosive"),
  c("coquin", "Avouer quel piment d'Espelette tu serais ce soir : douce, piquante, ou carrément explosive"),
  c("coquin", "Choisir un dessert (meringue) pour décrire ton état d'esprit face à {cible} ce soir", true),
  c("coquin", "Choisir un dessert (chantilly) pour décrire ton état d'esprit face à {cible} ce soir", true),
  c("coquin", "Choisir un dessert (crème brûlée) pour décrire ton état d'esprit face à {cible} ce soir", true),
  c("coquin", "Choisir un dessert (tablette de chocolat) pour décrire ton état d'esprit face à {cible} ce soir", true),
  c("coquin", "Choisir un dessert (caramel) pour décrire ton état d'esprit face à {cible} ce soir", true),
  c("coquin", "Choisir un dessert (sorbet) pour décrire ton état d'esprit face à {cible} ce soir", true),
  c("coquin", "Décrire en une phrase, sans un mot cru, ce qui se passe quand le fruit est « bien mûr »"),
  c("coquin", "Avouer ta position préférée… sur le canapé, façon chat qui s'étire au soleil"),

  c("coquin", "", true, false, true),
  c("coquin", "", true, false, true),

  // ------------------------------------------------------------
  // BRÛLANT — le plus assumé, toujours suggéré, jamais explicite
  // ------------------------------------------------------------
  c("brulant", "Faire une sextape avec {cible}, et dire laquelle des deux caméras filmerait le mieux", true),
  c("brulant", "Passer une nuit entière avec {cible}, portes closes, sans rien dire au groupe le lendemain", true),
  c("brulant", "Avouer le fantasme le plus fou que tu n'as jamais osé dire à voix haute"),
  c("brulant", "Décrire la dernière fois où tu as jouis rien qu'en y repensant"),
  c("brulant", "Avouer ce que tu ferais à {cible} si vous étiez seuls cette nuit", true),
  c("brulant", "Faire l'amour à {cible} cette nuit, et dire dans quelle pièce de la maison", true),
  c("brulant", "Avouer combien de fois tu as fantasmé sur quelqu'un dans cette pièce, ce soir"),
  c("brulant", "Décrire ta position préférée en un mot, sans détail"),
  c("brulant", "Avouer la dernière personne à qui tu as envoyé une photo très osée"),
  c("brulant", "Passer la nuit à Cracovie avec {cible}, et dire ce qui se passerait au retour", true),
  c("brulant", "Avouer si tu préfères dominer ou être dominé·e ce soir"),
  c("brulant", "Décrire le dernier rêve érotique dont tu te souviens, en une phrase"),
  c("brulant", "Avouer ce que tu murmurerais à {cible} juste avant de l'embrasser", true),
  c("brulant", "Faire une promesse brûlante à {cible} pour la fin de soirée", true),
  c("brulant", "Avouer le lieu le plus insolite où tu as déjà fait l'amour"),
  c("brulant", "Décrire en un mot ce que tu ressens en regardant {cible} ce soir", true),
  c("brulant", "Avouer ton safe word imaginaire, juste pour le fun"),
  c("brulant", "Raconter ta nuit la plus torride, sans nommer qui que ce soit"),
  c("brulant", "Avouer si tu préfères la lumière allumée ou éteinte, et pourquoi"),
  c("brulant", "Décrire le message le plus chaud que tu aies jamais reçu"),

  // — Grande série additionnelle (fruits, légumes, bestiaire, sucreries) —
  c("brulant", "Avouer à quel point ta nectarine est en feu rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ta mirabelle est brûlante d'impatience rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ton kiwi est électrique ce soir rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ton ananas est prêt à tout dévorer rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ton litchi est à fleur de peau rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ta grenade est sur le point de craquer rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ta mangue est irrésistible ce soir rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Avouer à quel point ta groseille est à deux doigts de l'incendie rien qu'en pensant à {cible} ce soir", true),
  c("brulant", "Décrire {cible} comme un litchi qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme une grenade qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme une mangue qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme une groseille qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme un abricot qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme une fraise qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme une cerise qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Décrire {cible} comme une clémentine qu'on n'a plus du tout envie de partager", true),
  c("brulant", "Avouer quel artichaut résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Avouer quel panais résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Avouer quel concombre résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Avouer quel radis résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Avouer quel piment résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Avouer quel poireau résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Avouer quel haricot vert résumerait le mieux ta nuit idéale, sans aucune retenue"),
  c("brulant", "Choisir l'animal (colibri) que tu deviendrais si {cible} te laissait faire, cette nuit", true),
  c("brulant", "Choisir l'animal (biche) que tu deviendrais si {cible} te laissait faire, cette nuit", true),
  c("brulant", "Choisir l'animal (ourson) que tu deviendrais si {cible} te laissait faire, cette nuit", true),
  c("brulant", "Choisir l'animal (chaton) que tu deviendrais si {cible} te laissait faire, cette nuit", true),
  c("brulant", "Choisir l'animal (paon) que tu deviendrais si {cible} te laissait faire, cette nuit", true),
  c("brulant", "Choisir l'animal (renard) que tu deviendrais si {cible} te laissait faire, cette nuit", true),
  c("brulant", "Avouer quelle guimauve fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quel nougat fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quelle meringue fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quel miel fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quelle praline fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quel caramel fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quelle chantilly fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Avouer quelle tablette de chocolat fond le plus vite quand tu penses à une nuit avec {cible}", true),
  c("brulant", "Décrire ta météo intérieure façon bulletin, entre « mûre à point » et « en feu »"),
  c("brulant", "Décrire ta météo intérieure façon bulletin, entre « toute fondante » et « brûlante d'impatience »"),
  c("brulant", "Décrire ta météo intérieure façon bulletin, entre « qui frétille » et « électrique ce soir »"),
  c("brulant", "Décrire ta météo intérieure façon bulletin, entre « bien sucrée » et « prête à tout dévorer »"),
  c("brulant", "Décrire ta météo intérieure façon bulletin, entre « au bord de déborder » et « à fleur de peau »"),
  c("brulant", "Décrire ta météo intérieure façon bulletin, entre « gourmande et pressée » et « sur le point de craquer »"),
  c("brulant", "Avouer dans quel jardin d'hiver tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quel potager tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quel hamac sous les étoiles tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quelle ruche tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quelle clairière tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quel verger tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quel grenier aux trésors tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Avouer dans quel jardin secret tu emmènerais {cible} pour une nuit entière, portes closes", true),
  c("brulant", "Choisir entre « nectarine », « artichaut » ou « guimauve » pour décrire ta faim de ce soir, et l'assumer devant tout le monde"),
  c("brulant", "Choisir entre « mirabelle », « panais » ou « nougat » pour décrire ta faim de ce soir, et l'assumer devant tout le monde"),
  c("brulant", "Choisir entre « kiwi », « concombre » ou « meringue » pour décrire ta faim de ce soir, et l'assumer devant tout le monde"),
  c("brulant", "Choisir entre « ananas », « radis » ou « miel » pour décrire ta faim de ce soir, et l'assumer devant tout le monde"),
  c("brulant", "Choisir entre « litchi », « piment » ou « praline » pour décrire ta faim de ce soir, et l'assumer devant tout le monde"),
  c("brulant", "Choisir entre « grenade », « poireau » ou « caramel » pour décrire ta faim de ce soir, et l'assumer devant tout le monde"),
  c("brulant", "Avouer ce que ton ourson intérieur ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ton chaton intérieur ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ton paon intérieur ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ton renard intérieur ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ta louve intérieure ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ton ocelot intérieur ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ton papillon intérieur ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Avouer ce que ta gazelle intérieure ferait à {cible} s'il n'y avait plus personne dans la pièce", true),
  c("brulant", "Décrire, avec une seule épice (poivre rose), l'intensité de ton envie ce soir"),
  c("brulant", "Décrire, avec une seule épice (gingembre), l'intensité de ton envie ce soir"),
  c("brulant", "Décrire, avec une seule épice (cannelle), l'intensité de ton envie ce soir"),
  c("brulant", "Décrire, avec une seule épice (safran), l'intensité de ton envie ce soir"),
  c("brulant", "Décrire, avec une seule épice (cardamome), l'intensité de ton envie ce soir"),
  c("brulant", "Décrire, avec une seule épice (clou de girofle), l'intensité de ton envie ce soir"),
  c("brulant", "Avouer quelle groseille tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quel abricot tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quelle fraise tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quelle cerise tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quelle clémentine tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quelle mandarine tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quelle datte tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Avouer quelle papaye tu laisserais {cible} peler entièrement, sans un mot", true),
  c("brulant", "Choisir le dessert (miel) que tu voudrais être, rien que pour {cible}, cette nuit", true),
  c("brulant", "Choisir le dessert (praline) que tu voudrais être, rien que pour {cible}, cette nuit", true),
  c("brulant", "Choisir le dessert (caramel) que tu voudrais être, rien que pour {cible}, cette nuit", true),
  c("brulant", "Choisir le dessert (chantilly) que tu voudrais être, rien que pour {cible}, cette nuit", true),
  c("brulant", "Choisir le dessert (tablette de chocolat) que tu voudrais être, rien que pour {cible}, cette nuit", true),
  c("brulant", "Choisir le dessert (sucre d'orge) que tu voudrais être, rien que pour {cible}, cette nuit", true),
  c("brulant", "Avouer combien de temps ton concombre tiendrait avant de craquer, face à {cible}", true),
  c("brulant", "Avouer combien de temps ton radis tiendrait avant de craquer, face à {cible}", true),
  c("brulant", "Avouer combien de temps ton piment tiendrait avant de craquer, face à {cible}", true),
  c("brulant", "Avouer combien de temps ton poireau tiendrait avant de craquer, face à {cible}", true),
  c("brulant", "Avouer combien de temps ton haricot vert tiendrait avant de craquer, face à {cible}", true),
  c("brulant", "Avouer combien de temps ton aubergine tiendrait avant de craquer, face à {cible}", true),
  c("brulant", "Décrire le moment exact où ton jardin secret est passé de « jardin d'hiver tranquille » à « incendie total »"),
  c("brulant", "Décrire le moment exact où ton jardin secret est passé de « potager tranquille » à « incendie total »"),
  c("brulant", "Décrire le moment exact où ton jardin secret est passé de « hamac sous les étoiles tranquille » à « incendie total »"),
  c("brulant", "Décrire le moment exact où ton jardin secret est passé de « ruche tranquille » à « incendie total »"),
  c("brulant", "Décrire le moment exact où ton jardin secret est passé de « clairière tranquille » à « incendie total »"),
  c("brulant", "Décrire le moment exact où ton jardin secret est passé de « verger tranquille » à « incendie total »"),
  c("brulant", "Avouer quel animal (renard) prendrait le dessus en toi si {cible} te chuchotait un seul mot ce soir", true),
  c("brulant", "Avouer quel animal (louve) prendrait le dessus en toi si {cible} te chuchotait un seul mot ce soir", true),
  c("brulant", "Avouer quel animal (ocelot) prendrait le dessus en toi si {cible} te chuchotait un seul mot ce soir", true),
  c("brulant", "Avouer quel animal (papillon) prendrait le dessus en toi si {cible} te chuchotait un seul mot ce soir", true),
  c("brulant", "Avouer quel animal (gazelle) prendrait le dessus en toi si {cible} te chuchotait un seul mot ce soir", true),
  c("brulant", "Avouer quel animal (hirondelle) prendrait le dessus en toi si {cible} te chuchotait un seul mot ce soir", true),
  c("brulant", "Choisir la métaphore la plus brûlante (fruit, épice ou dessert) pour décrire ce que tu ressens là, maintenant"),
  c("brulant", "Avouer quel fruit défendu (clémentine) tu croquerais sans une seconde d'hésitation ce soir, et pourquoi lui"),
  c("brulant", "Avouer quel fruit défendu (mandarine) tu croquerais sans une seconde d'hésitation ce soir, et pourquoi lui"),
  c("brulant", "Avouer quel fruit défendu (datte) tu croquerais sans une seconde d'hésitation ce soir, et pourquoi lui"),
  c("brulant", "Avouer quel fruit défendu (papaye) tu croquerais sans une seconde d'hésitation ce soir, et pourquoi lui"),
  c("brulant", "Avouer quel fruit défendu (prune) tu croquerais sans une seconde d'hésitation ce soir, et pourquoi lui"),
  c("brulant", "Avouer quel fruit défendu (pêche) tu croquerais sans une seconde d'hésitation ce soir, et pourquoi lui"),

  c("brulant", "", true, false, true),
  c("brulant", "", true, false, true),

  // ------------------------------------------------------------
  // DÉFI — une vraie action à réaliser, validée manuellement
  // ensuite (fait / pas fait), tout de suite ou plus tard.
  // ------------------------------------------------------------
  c("defi", "Envoie une photo de toi en train de danser, là, maintenant.", false, true),
  c("defi", "Fais 20 pompes devant tout le monde.", false, true),
  c("defi", "Réalise une vidéo de 10 secondes où tu imites {cible}.", true, true),
  c("defi", "Envoie un message vocal chantant à un contact choisi par le groupe.", false, true),
  c("defi", "Tente une roue (ou une tentative sincère) devant tout le monde.", false, true),
  c("defi", "Bois d'un trait un mélange improbable choisi par le groupe (sans alcool fort).", false, true),
  c("defi", "Appelle un proche et récite-lui un poème improvisé.", false, true),
  c("defi", "Poste une story avec la légende imposée par le groupe.", false, true),
  c("defi", "Échange un vêtement avec {cible} pour le reste de la soirée.", true, true),
  c("defi", "Fais un compliment filmé à chaque joueur, façon interview.", false, true),
  c("defi", "Dessine {cible} en 60 secondes chrono et montre le résultat.", true, true),
  c("defi", "Envoie ta pire photo d'identité à un proche avec un message très flatteur.", false, true),
  c("defi", "Fais deviner un mot imposé en mimant, sans parler, pendant une minute.", false, true),
  c("defi", "Chante filmé le refrain d'une chanson imposée par le groupe.", false, true),
  c("defi", "Improvise une chorégraphie de 15 secondes sur la musique choisie par le groupe.", false, true),
  c("defi", "Chuchote un secret inoffensif à l'oreille de {cible} et laisse le groupe deviner.", true, true),
  c("defi", "Fais un shot de jus de citron pur devant tout le monde.", false, true),
  c("defi", "Envoie tout de suite un message d'excuse absurde à quelqu'un du groupe.", false, true),
  c("defi", "Traverse la pièce en marchant en crabe.", false, true),
  c("defi", "Fais une déclaration d'amour improvisée et sincère à un objet de la pièce.", false, true),
  c("defi", "Fais un strip-tease (habillé) de 15 secondes sur la musique imposée.", false, true),
  c("defi", "Envoie un message doux et osé à {cible}, et montre-le au groupe une fois envoyé.", true, true),
];

// Attribution des identifiants et vérification de cohérence
const CARTES = CARTES_BRUTES.map((carte, i) => ({
  id: `c${String(i + 1).padStart(3, "0")}`,
  ...carte,
}));

// ------------------------------------------------------------
// Réactions des joueurs — 5 par genre, une lettre imposée
// ------------------------------------------------------------
const REACTIONS_M = [
  { id: "m1", lettre: "M", texte: "Miam !", profil: "envie" },
  { id: "m2", lettre: "M", texte: "Mille fois non !", profil: "refus" },
  { id: "m3", lettre: "M", texte: "Ma foi… pourquoi pas ?", profil: "hesitation" },
  { id: "m4", lettre: "M", texte: "Moi d'abord !", profil: "fonceuse" },
  { id: "m5", lettre: "M", texte: "Mouillée d'avance 💦", profil: "coquin" },
];

const REACTIONS_B = [
  { id: "b1", lettre: "B", texte: "Bueno !", profil: "envie" },
  { id: "b2", lettre: "B", texte: "Bof…", profil: "hesitation" },
  { id: "b3", lettre: "B", texte: "Banco, je fonce !", profil: "fonceur" },
  { id: "b4", lettre: "B", texte: "Basta !", profil: "refus" },
  { id: "b5", lettre: "B", texte: "Bandant 😏", profil: "coquin" },
];

// Paquet dédié aux cartes Défi — indépendant du pack M/B du joueur
const REACTIONS_D = [
  { id: "d1", lettre: "D", texte: "Dingue, j'adore !", profil: "envie" },
  { id: "d2", lettre: "D", texte: "Doucement, laisse-moi réfléchir…", profil: "hesitation" },
  { id: "d3", lettre: "D", texte: "Direct, je fonce !", profil: "fonceur" },
  { id: "d4", lettre: "D", texte: "Décliné.", profil: "refus" },
  { id: "d5", lettre: "D", texte: "Dévergondé·e à souhait 😏", profil: "coquin" },
];

// ------------------------------------------------------------
// Gages et récompenses
// ------------------------------------------------------------
const RECOMPENSES_GAGNANT = [
  "Tu choisis le gage du/de la dernier·ère dans la liste, ou tu en inventes un.",
  "Tu es servi·e par les autres joueurs pendant 10 minutes (boisson, snack).",
  "Tu gagnes une carte Véto bonus pour la prochaine partie.",
  "Tu poses une question cash à un joueur de ton choix, qui doit répondre sans véto.",
];

const GAGES_DOUX = [
  "Imiter un animal au choix du groupe pendant une minute.",
  "Parler avec l'accent imposé par le groupe pendant trois tours.",
  "Faire un compliment sincère à chaque joueur, un par un.",
  "Offrir la tournée ou le dessert à toute la tablée.",
  "Raconter une blague, et si elle ne fait rire personne, en raconter une deuxième.",
  "Envoyer un mème choisi par le groupe dans ton groupe de discussion familial.",
];

const GAGES_PIQUANT = [
  "Raconter ton pire rendez-vous amoureux, en détail.",
  "Danser sensuellement pendant trente secondes devant le groupe.",
  "Faire un massage de deux minutes à un joueur consentant.",
  "Envoyer un texto choisi par le groupe, relu et validé par toi avant l'envoi.",
  "Répondre sans mentir à une question cash posée par chaque joueur.",
  "Laisser le groupe fouiller ta galerie photo pendant une minute (tu peux en retirer une avant).",
];

const GAGES_FOU = [
  "Chanter en public, dans la rue ou sur un balcon.",
  "Appeler un ami pour lui faire une déclaration absurde et assumée.",
  "Laisser le groupe choisir ta photo de profil pendant une heure.",
  "Porter un vêtement du gagnant pendant le reste de la soirée.",
  "Envoyer un message vocal chanté à la dernière personne contactée.",
  "Faire une story publique où tu avoues ta défaite, façon grand discours.",
];

const NIVEAUX_GAGES = {
  doux: GAGES_DOUX,
  piquant: GAGES_PIQUANT,
  fou: GAGES_FOU,
};

const BoomCartes = {
  NIVEAUX,
  CARTES,
  REACTIONS_M,
  REACTIONS_B,
  REACTIONS_D,
  RECOMPENSES_GAGNANT,
  NIVEAUX_GAGES,
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = BoomCartes;
} else if (typeof window !== "undefined") {
  window.BoomCartes = BoomCartes;
}
